ScaleModeling.WebUI/Controllers/EventController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class EventController : Controller
    {
        private IRepository<Event> eventRepository;

        public EventController(IRepository<Event> eventRepositoryParam)
        {
            this.eventRepository = eventRepositoryParam;
        }

        public ViewResult Index()
        {
            return View( eventRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteEvent(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", eventRepository.GetAll.ToList() );
            }


            Event currentEvent = eventRepository.GetAll.Where( e => e.Id == id ).AsEnumerable().First();

            currentEvent.Viewed += 1;


            await eventRepository.Update( currentEvent );

            await eventRepository.SaveChangesAsync();


            return View( currentEvent );
        }
    }
}

ScaleModeling.WebUI/Controllers/ForumController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class ForumController : Controller
    {
        private IRepository<ForumTopic> forumTopicRepository;

        public ForumController(IRepository<ForumTopic> forumTopicRepositoryParam)
        {
            this.forumTopicRepository = forumTopicRepositoryParam;
        }

        public ActionResult Index()
        {
            return View( forumTopicRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteTopic(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", forumTopicRepository.GetAll.ToList() );
            }


            ForumTopic currentTopic = forumTopicRepository.GetAll.Where( ft => ft.Id == id ).AsEnumerable().First();

            currentTopic.Viewed += 1;


            await forumTopicRepository.Update( currentTopic );

            await forumTopicRepository.SaveChangesAsync();


            return View( currentTopic );
        }
    }
}

ScaleModeling.WebUI/Controllers/ShopController.cs
using System.Linq;
using System.Web.Mvc;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IRepository<Product> productRepository;

        public ShopController(IRepository<Product> productRepositoryParam)
        {
            this.productRepository = productRepositoryParam;
        }

        public ViewResult Index()
        {
            return View(productRepository.GetAll.ToList());
        }

        public ViewResult GetConcreteProduct(int id)
        {
            return View( productRepository.GetAll.Where( p => p.Id == id ).AsEnumerable().First() );
        }
    }
}

ScaleModeling.WebUI/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScaleModeling.WebUI.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            return View();
        }
    }
}

ScaleModeling.WebUI/Controllers/WorkController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class WorkController : Controller
    {
        private IRepository<Work> workRepository;

        public WorkController(IRepository<Work> workRepositoryParam)
        {
            this.workRepository = workRepositoryParam;
        }

        public ActionResult Index()
        {
            return View( workRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteWork(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", workRepository.GetAll.ToList() );
            }


            Work currentWork = workRepository.GetAll.Where( w => w.Id == id ).AsEnumerable().First();

            currentWork.Viewed += 1;


            await workRepository.Update( currentWork );

            await workRepository.SaveChangesAsync();


            return View( currentWork );
        }
    }
}

ScaleModeling.WebUI/Views/Shop/GetConcreteProduct.cshtml
@using ScaleModeling.Domain.Entities
@model Product

@{
	ViewBag.Title = Model.Name;
}

@section Links{
	<li>
		<div class="navigation-couple">
			<img src="~/Content/Images/avatar.jpg" class="clickable-content img-circle logo-image" data-href="@Url.Action("Index", "Manage")" />
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Home")" class="glyphicon glyphicon-home">
				<div>Главная</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Shop")" class="active glyphicon glyphicon-usd">
				<div>Магазин</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Event")" class="glyphicon glyphicon-bullhorn">
				<div>События</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Article")" class="glyphicon glyphicon-list-alt">
				<div>Статьи</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Forum")" class="glyphicon glyphicon-pencil">
				<div>Форум</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Video")" class="glyphicon glyphicon-film">
				<div>Видео</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Work")" class="glyphicon glyphicon-wrench">
				<div>Работы</div>
			</a>
		</div>
	</li>
}

<div class="row">
	qweqw
</div>

ScaleModeling.WebUI/Views/Shop/Index.cshtml
@{
	ViewBag.Title = "Магазин";
}

@section Links{
	<li>
		<div class="navigation-couple">
			<img src="~/Content/Images/avatar.jpg" class="clickable-content img-circle logo-image" data-href="@Url.Action("Index", "Manage")" />
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Home")" class="glyphicon glyphicon-home">
				<div>Главная</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Shop")" class="active glyphicon glyphicon-usd">
				<div>Магазин</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Event")" class="glyphicon glyphicon-bullhorn">
				<div>События</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Article")" class="glyphicon glyphicon-list-alt">
				<div>Статьи</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Forum")" class="glyphicon glyphicon-pencil">
				<div>Форум</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Video")" class="glyphicon glyphicon-film">
				<div>Видео</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Work")" class="glyphicon glyphicon-wrench">
				<div>Работы</div>
			</a>
		</div>
	</li>
}