ScaleModeling.WebUI/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;
using ScaleModeling.WebUI.Models;

namespace ScaleModeling.WebUI.Controllers
{
    public class ArticleController : Controller
    {
        private IRepository<Article> articleRepository;
        private IRepository<ArticleComment> articleCommentsRepository;

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                _userManager = value;
            }
        }

        public ArticleController(IRepository<Article> articleRepositoryParam, IRepository<ArticleComment> articleCommentsRepositoryParam)
        {
            this.articleRepository = articleRepositoryParam;

            this.articleCommentsRepository = articleCommentsRepositoryParam;
        }

        public ViewResult Index()
        {
            return View( articleRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteArticle(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", articleRepository.GetAll.ToList() );
            }


            Article currentArticle = articleRepository.GetAll.Where( a => a.Id == id ).AsEnumerable().First();

            currentArticle.Viewed += 1;


            await articleRepository.Update( currentArticle );

            await articleRepository.SaveChangesAsync();


            return View( currentArticle );
        }

        public PartialViewResult CommentsOpen(int id = 0)
        {
            if (id == 0)
            {
                throw new Exception( "Article id = 0, article is undefined!" );
            }


            List<ArticleComment> articleComments = articleCommentsRepository.GetAll.Where( ac => ac.ArticleId == id ).ToList();


            return PartialView( articleComments );
        }

        public PartialViewResult CommentField(int id = 0)
        {
            if (User.Identity.IsAuthenticated)
            {
                User currentUser = UserManager.FindById( User.Identity.GetUserId<int>() );

                return PartialView( new CommenterInfoViewModel { UserName = User.Identity.Name,
                                                                 CommentedEntityId = id,
                                                                 Rating = currentUser.UserDetail.Rating,
                                                                 ArticleCount = currentUser.Articles.Count,
                                                                 WorksCount = currentUser.Works.Count, } );
            }

            return PartialView( "NotAuthenticated" );
        }



        [HttpPost]
        public async Task<ViewResult> CreateComment(CommentViewModel comment, int id)
        {
            await articleCommentsRepository.Create( new ArticleComment { ArticleId = id, AuthorId = User.Identity.GetUserId<int>(), CreationDate = DateTime.Now, Text = comment.CommentText } );

            await articleCommentsRepository.SaveChangesAsync();

            return View( "GetConcreteArticle", articleRepository.GetAll.Where( a => a.Id == id ).AsEnumerable().First() );
        }




        public async Task<int> AddLike(int id = 0)
        {
            if (id == 0)
            {
                throw new Exception( "Article id = 0, article is undefined!" );
            }


            Article currentArticle = await articleRepository.GetEntityById( id );

            int userLikedId = User.Identity.GetUserId<int>();

            if (userLikedId != default( int ))
            {
                ArticleLiked currentLike = new ArticleLiked { ArticleId = currentArticle.Id, UserId = userLikedId, LikedDate = DateTime.Now };


                if (currentArticle.Likes.Any( a => a.ArticleId == currentLike.ArticleId && a.UserId == currentLike.UserId ))
                {
                    currentArticle.Likes.RemoveAll( a => a.ArticleId == currentLike.ArticleId && a.UserId == currentLike.UserId );
                    await articleRepository.SaveChangesAsync();
                }

                else
                {
                    currentArticle.Likes.Add( currentLike );
                    await articleRepository.SaveChangesAsync();
                }

            }

            return currentArticle.Likes.Count();
        }
    }
}

ScaleModeling.WebUI/Controllers/EventController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class EventController : Controller
    {
        private IRepository<Event> eventRepository;

        public EventController(IRepository<Event> eventRepositoryParam)
        {
            this.eventRepository = eventRepositoryParam;
        }

        public ViewResult Index()
        {
            return View( eventRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteEvent(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", eventRepository.GetAll.ToList() );
            }


            Event currentEvent = eventRepository.GetAll.Where( e => e.Id == id ).AsEnumerable().First();

            currentEvent.Viewed += 1;


            await eventRepository.Update( currentEvent );

            await eventRepository.SaveChangesAsync();


            return View( currentEvent );
        }
    }
}

ScaleModeling.WebUI/Controllers/ForumController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class ForumController : Controller
    {
        private IRepository<ForumTopic> forumTopicRepository;

        public ForumController(IRepository<ForumTopic> forumTopicRepositoryParam)
        {
            this.forumTopicRepository = forumTopicRepositoryParam;
        }

        public ActionResult Index()
        {
            return View( forumTopicRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteTopic(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", forumTopicRepository.GetAll.ToList() );
            }


            ForumTopic currentTopic = forumTopicRepository.GetAll.Where( ft => ft.Id == id ).AsEnumerable().First();

            currentTopic.Viewed += 1;


            await forumTopicRepository.Update( currentTopic );

            await forumTopicRepository.SaveChangesAsync();


            return View( currentTopic );
        }
    }
}

ScaleModeling.WebUI/Controllers/ShopController.cs
using System.Linq;
using System.Web.Mvc;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IRepository<Product> productRepository;

        public ShopController(IRepository<Product> productRepositoryParam)
        {
            this.productRepository = productRepositoryParam;
        }

        public ViewResult Index()
        {
            return View(productRepository.GetAll.ToList());
        }

        public ViewResult GetConcreteProduct(int id)
        {
            return View( productRepository.GetAll.Where( p => p.Id == id ).AsEnumerable().First() );
        }
    }
}

ScaleModeling.WebUI/Controllers/WorkController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

using ScaleModeling.Domain.Abstract;
using ScaleModeling.Domain.Entities;

namespace ScaleModeling.WebUI.Controllers
{
    public class WorkController : Controller
    {
        private IRepository<Work> workRepository;

        public WorkController(IRepository<Work> workRepositoryParam)
        {
            this.workRepository = workRepositoryParam;
        }

        public ActionResult Index()
        {
            return View( workRepository.GetAll.ToList() );
        }

        public async Task<ViewResult> GetConcreteWork(int id = 0)
        {
            if (id == 0)
            {
                return View( "Index", workRepository.GetAll.ToList() );
            }


            Work currentWork = workRepository.GetAll.Where( w => w.Id == id ).AsEnumerable().First();

            currentWork.Viewed += 1;


            await workRepository.Update( currentWork );

            await workRepository.SaveChangesAsync();


            return View( currentWork );
        }
    }
}

ScaleModeling.WebUI/Views/Article/CommentField.cshtml
@using ScaleModeling.WebUI.Models
@model CommenterInfoViewModel

<div class="container pull-left full-commentator-info">
	<div class="pull-left">
		<img src="/Content/Images/avatar.jpg" class="clickable-content img-circle sm-avatar-image pull-left" data-href="#">

		<div class="commentator-info">
			<span class="label label-author">
				<span class="glyphicon glyphicon-user"></span>
				<span class="viewed">@Model.UserName</span>
			</span>
			<span class="label label-viewed">
				<span class="glyphicon glyphicon-star"></span>
				<span class="viewed">@Model.Rating</span>
			</span>
			<span class="label label-works-and-articles">
				<span class="glyphicon glyphicon-wrench"></span>
				<span class="viewed">@Model.WorksCount</span>
			</span>
			<span class="label label-works-and-articles">
				<span class="glyphicon glyphicon-list-alt"></span>
				<span class="viewed">@Model.ArticleCount</span>
			</span>
		</div>
	</div>
</div>

<div class="pull-left textarea">
	@using (Html.BeginForm( "CreateComment", "Article", new { id = Model.CommentedEntityId }, FormMethod.Post, new { @class = "form-group" } ))
	{
		<div class="pull-left textarea">
			@Html.TextArea( "CommentText", "Текст комментария...", new { @class = "form-control" } )
		</div>
		<div class="pull-left">
			<button class="btn btn-primary" type="submit">Отправить</button>
		</div>
	}
</div>

ScaleModeling.WebUI/Views/Article/CommentsOpen.cshtml
@model IEnumerable<ScaleModeling.Domain.Entities.ArticleComment>


@if (Model.Count() > 0)
{
	foreach (var comment in Model)
	{
		<div class="row article-comments-container well">
			<div class="col-md-3 pull-left">
				<div class="pull-left">
					<img src="/Content/Images/avatar.jpg" class="clickable-content img-circle sm-avatar-image pull-left" data-href="#">
					<div class="container pull-left commentator-info">
						<span class="label label-author">
							<span class="glyphicon glyphicon-user"></span>
							<span class="viewed">@comment.Author.UserName</span>
						</span>
						<span class="label label-viewed">
							<span class="glyphicon glyphicon-star"></span>
							<span class="viewed">@comment.Author.UserDetail.Rating</span>
						</span>
						<span class="label label-works-and-articles">
							<span class="glyphicon glyphicon-wrench"></span>
							<span class="viewed">@comment.Author.Works.Count()</span>
						</span>
						<span class="label label-works-and-articles">
							<span class="glyphicon glyphicon-list-alt"></span>
							<span class="viewed">@comment.Author.Articles.Count()</span>
						</span>
						<span class="label label-date-comment">
							<span class="glyphicon glyphicon-time"></span>
							<span class="viewed">@comment.CreationDate</span>
						</span>
					</div>
				</div>
			</div>
			<div class="col-md-9 pull-left">
				@comment.Text
			</div>
		</div>
	}
}

ScaleModeling.WebUI/Views/Article/GetConcreteArticle.cshtml
@using ScaleModeling.Domain.Entities
@model Article

@{
	ViewBag.Title = Model.Title;

	AjaxOptions ajaxOptionsComments = new AjaxOptions
	{
		UpdateTargetId = "comments"
	};

	AjaxOptions ajaxOptionsLikes = new AjaxOptions
	{
		UpdateTargetId = "like-count"
	};
}

@section Links{
	<li>
		<div class="navigation-couple">
			<img src="~/Content/Images/avatar.jpg" class="clickable-content img-circle logo-image" data-href="@Url.Action("Index", "Manage")" />
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Home")" class="glyphicon glyphicon-home">
				<div>Главная</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Shop")" class="glyphicon glyphicon-usd">
				<div>Магазин</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Event")" class="glyphicon glyphicon-bullhorn">
				<div>События</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Article")" class="active glyphicon glyphicon-list-alt">
				<div>Статьи</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Forum")" class="glyphicon glyphicon-pencil">
				<div>Форум</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Video")" class="glyphicon glyphicon-film">
				<div>Видео</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Work")" class="glyphicon glyphicon-wrench">
				<div>Работы</div>
			</a>
		</div>
	</li>
}

<div class="row title-container">
	<div class="container pull-left">
		<span class="label label-date">
			<span class="glyphicon glyphicon-time"></span>
			<span class="viewed">@Model.CreationDate.ToString().Substring( 0, 10 )</span>
		</span>
		<span class="label label-author">
			<span class="glyphicon glyphicon-user"></span>
			<span class="viewed">@Model.Author.UserName</span>
		</span>
		<span class="label label-viewed">
			<span class="glyphicon glyphicon-eye-open"></span>
			<span class="viewed">@Model.Viewed</span>
		</span>
		<span class="label label-viewed">
			<span class="glyphicon glyphicon-thumbs-up"></span>
			<span class="viewed">@Model.Likes.Count</span>
		</span>
		<span class="label label-viewed">
			<span class="glyphicon glyphicon-comment"></span>
			<span class="viewed">@Model.Comments.Count</span>
		</span>
	</div>
	<div class="pull-right">
		<div class="aw-title">
			<strong>
				@Model.Title
			</strong>
		</div>
	</div>
</div>
<div class="row body-container">
	@Model.Description
</div>
<div class="row footer-container">
	<div class="container pull-right">
		@using (Ajax.BeginForm( "CommentsOpen", new { id = Model.Id }, ajaxOptionsComments ))
		{
			<button type="submit" class="btn btn-primary pull-right">
				<span class="glyphicon glyphicon-comment"></span>
				<span class="viewed">@Model.Comments.Count()</span>
			</button>
		}
		@using (Ajax.BeginForm( "AddLike", new { id = Model.Id }, ajaxOptionsLikes ))
		{
			<button class="btn btn-primary pull-right" id="button-likes">
				<span class="glyphicon glyphicon-thumbs-up"></span>
				<span class="viewed" id="like-count">@Model.Likes.Count</span>
			</button>
		}
	</div>
	@Html.Action( "CommentField", new { id = Model.Id } )
</div>
<div id="comments">
</div>

ScaleModeling.WebUI/Views/Article/Index.cshtml
@{
	ViewBag.Title = "Статьи";
}

@section Links{
	<li>
		<div class="navigation-couple">
			<img src="~/Content/Images/avatar.jpg" class="clickable-content img-circle logo-image" data-href="@Url.Action("Index", "Manage")" />
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Home")" class="glyphicon glyphicon-home">
				<div>Главная</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Shop")" class="glyphicon glyphicon-usd">
				<div>Магазин</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Event")" class="glyphicon glyphicon-bullhorn">
				<div>События</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Article")" class="active glyphicon glyphicon-list-alt">
				<div>Статьи</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Forum")" class="glyphicon glyphicon-pencil">
				<div>Форум</div>
			</a>
		</div>

	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Video")" class="glyphicon glyphicon-film">
				<div>Видео</div>
			</a>
		</div>
	</li>
	<li>
		<div class="navigation-couple">
			<a href="@Url.Action("Index", "Work")" class="glyphicon glyphicon-wrench">
				<div>Работы</div>
			</a>
		</div>
	</li>
}

<div class="container-fluid">
	<div class="row">

		<div class="col-md-5 col-md-offset-1">
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название длинной предлинной очень длинной статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-5 col-md-offset-1">
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
			<div class="row well">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<p>Описание  это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<span class="pull-left label label-primary">30.05.1993</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<span class="pull-left">Название статьи</span>
						</div>
						<div class="col-md-6">
							<span class="pull-right">Автор</span>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

ScaleModeling.WebUI/Views/Article/NotAuthenticated.cshtml
<div>
	Необходимо авторизоватся
</div>